global:
  slack_api_url: "https://hooks.slack.com/services/<api-token>"
  resolve_timeout: 20s

route:
  group_by: ['instance', 'severity']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h
  receiver: slack

receivers:
- name: slack
  slack_configs:
  - send_resolved: true
    channel: alerts
    username: '{{ template "slack.default.username" . }}'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: '{{ template "slack.default.title" . }}'
    text: |-
      {{ range .Alerts }}
        *Desc:* {{ .Annotations.description }}
      {{ end }}
    fallback: '{{ template "slack.default.fallback" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: '{{ template "slack.default.iconurl" . }}'