{
 "title": "Uptime",
 "description": "Uptime",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All alerts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Down Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"InstanceDown\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "High Memory Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"OutOfMemory\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "High CPU Node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"CpuLoad\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Number of systemd failed",
   "type": "singlestat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{state=\"failed\"})"
    }
   ]
  },
  {
   "title": "Number of active alerts",
   "type": "singlestat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", instance=~\"$instance\"})",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "labelSelector": "*", "legendFormat": "{{ instance }}", "target": "Query", "type": "table" }
   ]
  },
  {
   "title": "Systemd Failed",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"failed\"} == 1"
    }
   ]
  }
 ]
}