groups:
- name: instance.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
      summary: "Instance {{ $labels.instance }} down"

  - alert: ServiceDown
    expr: sum(node_systemd_unit_state{state="failed"}) > 1
    for: 30s
    labels:
      severity: critical
    annotations:
      description: 'service {{ $labels.name }} of instance {{ $labels.instance }} has been down.'
      summary: "Service {{ $labels.name }} down"