groups:
- name: systemd.rules
  rules:
  - alert: SystemdServiceFailed
    expr: node_systemd_unit_state{state="failed"} == 1
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "SystemD service failed (instance {{ $labels.instance }})"
      description: "Service {{ $labels.name }} failed\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"